name: Docker Image CI

on:
  release:
    types: [published]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Build the Docker image
            working-directory: docker
            run: docker build -t samvandenabeele09/novacan:pr-${{ github.event.pull_request.number }} .
          - name: Push new docker image
            working-directory: docker
            run: docker push samvandenabeele09/novacan:pr-${{ github.event.pull_request.number }}